package com.bsnbase.sdk.entity.resp.fabric;

import com.bsnbase.sdk.entity.base.IBody;
import lombok.Data;

/**
 * Response parameters of get transaction data interface
 */

@Data
public class ResTransData implements IBody {
    /**
     * Transaction ID
     */
    String txId;
    /**
     * Transaction data
     * Note：String generated by base64 algorithm
     */
    String transData;

    @Override
    public String getEncryptionValue() {
        return (this.txId == null ? "" : this.txId) + (this.transData == null ? "" : this.transData);
    }
}
