package com.bsnbase.sdk.entity.req.fiscobcos;

import com.bsnbase.sdk.entity.base.IBody;
import lombok.Data;

/**
 * Request parameters for FISCO-BCOS calling the smart contract interface in Key Trust Mode
 */
@Data
public class ReqKeyEscrow implements IBody {
    /**
     * User ID
     * Note: The user ID generated by calling the user registration interface
     */
    String userId;
    /**
     * Contract name
     */
    String contractName;
    /**
     * Method name
     */
    String funcName;
    /**
     * Method parameters  Converting array format parameters to json string assignment
     */
    String funcParam;

    @Override
    public String getEncryptionValue() {

        String str = (this.userId == null ? "" : this.userId);
        str += (this.contractName == null ? "" : this.contractName);
        str += (this.funcName == null ? "" : this.funcName);
        str += (this.funcParam == null ? "" : this.funcParam);
        return str;
    }
}
